const CollectionTypes = {
    ADD_PRODUCTS_START: 'ADD_PRODUCTS_START',
    ADD_PRODUCTS: 'ADD_PRODUCTS',
    ADD_FAIL:'ADD_FAIL',
    LOADING: 'LOADING',
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START'
}

export default CollectionTypes